[[constraint]]
  name = "github.com/Telefonica/govice"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"
