version: '2'

services:

  seed:
    image: dockerhub.hi.inet/telefonica/seed-golang:${BUILD_VERSION}
    ports:
      - 9000
    networks:
      - net
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb
      LOG_LEVEL: INFO

  mongodb:
    image: mongo:3.4.9
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - net

networks:
  net:
